### ISSUE TITLE
Deprecated selector in `atom-espresso-soda-theme/index.less`

### ISSUE THREAD

**Issue by roblan** [martinwolf/atom-espresso-soda-theme#6]
In `atom-espresso-soda-theme/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.comment,
.comment .punctuation` => `.syntax--comment,
.syntax--comment .syntax--punctuation`

* `.comment.block.preprocessor` => `.syntax--comment.syntax--block.syntax--preprocessor`

* `.has-selection .comment.documentation,
.has-selection .comment.block.documentation` => `.has-selection .syntax--comment.syntax--documentation,
.has-selection .syntax--comment.syntax--block.syntax--documentation`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword,
.storage` => `.syntax--keyword,
.syntax--storage`

* `.storage.type,
.support.type` => `.syntax--storage.syntax--type,
.syntax--support.syntax--type`

* `.constant.language,
.support.constant,
.variable.language` => `.syntax--constant.syntax--language,
.syntax--support.syntax--constant,
.syntax--variable.syntax--language`

* `.variable,
.support.variable` => `.syntax--variable,
.syntax--support.syntax--variable`

* `.variable .punctuation` => `.syntax--variable .syntax--punctuation`

* `.entity.name.function,
.support.function,
.entity` => `.syntax--entity.syntax--name.syntax--function,
.syntax--support.syntax--function,
.syntax--entity`

* `.entity.name.type,
.entity.other.inherited-class,
.support.class` => `.syntax--entity.syntax--name.syntax--type,
.syntax--entity.syntax--other.syntax--inherited-class,
.syntax--support.syntax--class`

* `.entity.name.exception` => `.syntax--entity.syntax--name.syntax--exception`

* `.constant.numeric,
.constant` => `.syntax--constant.syntax--numeric,
.syntax--constant`

* `.punctuation` => `.syntax--punctuation`

* `.constant.character,
.string` => `.syntax--constant.syntax--character,
.syntax--string`

* `.string .punctuation` => `.syntax--string .syntax--punctuation`

* `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`

* `.string .source,
.text .source` => `.syntax--string .syntax--source,
.syntax--text .syntax--source`

* `.meta.tag.sgml.doctype` => `.syntax--meta.syntax--tag.syntax--sgml.syntax--doctype`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.meta.tag .string .punctuation` => `.syntax--meta.syntax--tag .syntax--string .syntax--punctuation`

* `.punctuation.definition.tag` => `.syntax--punctuation.syntax--definition.syntax--tag`

* `.constant.character.entity` => `.syntax--constant.syntax--character.syntax--entity`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.meta.tag .string.quoted,
.meta.tag .string.quoted .constant.character.entity` => `.syntax--meta.syntax--tag .syntax--string.syntax--quoted,
.syntax--meta.syntax--tag .syntax--string.syntax--quoted .syntax--constant.syntax--character.syntax--entity`

* `.meta.selector,
.meta.selector .entity,
.meta.selector .entity .punctuation,
.entity.name.tag.css` => `.syntax--meta.syntax--selector,
.syntax--meta.syntax--selector .syntax--entity,
.syntax--meta.syntax--selector .syntax--entity .syntax--punctuation,
.syntax--entity.syntax--name.syntax--tag.syntax--css`

* `.meta.property-name,
.support.type.property-name` => `.syntax--meta.syntax--property-name,
.syntax--support.syntax--type.syntax--property-name`

* `.meta.property-value .constant.numeric,
.meta.property-value .constant,
.meta.property-value .keyword` => `.syntax--meta.syntax--property-value .syntax--constant.syntax--numeric,
.syntax--meta.syntax--property-value .syntax--constant,
.syntax--meta.syntax--property-value .syntax--keyword`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.italic` => `.syntax--markup.syntax--italic`

* `.markup.error` => `.syntax--markup.syntax--error`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.output,
.markup.raw` => `.syntax--markup.syntax--output,
.syntax--markup.syntax--raw`

* `.markup.prompt` => `.syntax--markup.syntax--prompt`

* `.markup.heading` => `.syntax--markup.syntax--heading`

* `.markup.bold` => `.syntax--markup.syntax--bold`

* `.markup.traceback` => `.syntax--markup.syntax--traceback`

* `.markup.underline` => `.syntax--markup.syntax--underline`

* `.meta.diff.range,
.meta.diff.index,
.meta.separator` => `.syntax--meta.syntax--diff.syntax--range,
.syntax--meta.syntax--diff.syntax--index,
.syntax--meta.syntax--separator`

* `.meta.diff.header.from-file` => `.syntax--meta.syntax--diff.syntax--header.syntax--from-file`

* `.meta.diff.header.to-file` => `.syntax--meta.syntax--diff.syntax--header.syntax--to-file`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by stackptr** [comment]
I opened #7 to resolve. Tested locally to resolve Depreciator Cop warning.
